<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>图纸空间的打印测试 - 编程大白的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="图纸空间的打印测试" />
<meta property="og:description" content="研究测试了一天，搞定了。深入认真研究清楚一个问题，功力一下子就升了一级。
&gt;&gt;&gt; # -*- coding: utf-8 -*- &gt;&gt;&gt; from pyautocad import Autocad,APoint &gt;&gt;&gt; import pyautocad.types &gt;&gt;&gt; import math &gt;&gt;&gt; import os &gt;&gt;&gt; import time &gt;&gt;&gt; import win32com.client &gt;&gt;&gt; import pythoncom &gt;&gt;&gt; def vtFloat(list): &#34;&#34;&#34;列表转化为浮点数&#34;&#34;&#34; return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, list) &gt;&gt;&gt; def vtInt(list): &#34;&#34;&#34;列表转化为整数&#34;&#34;&#34; return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_I2, list) &gt;&gt;&gt; def vtVariant(list): &#34;&#34;&#34;列表转化为变体&#34;&#34;&#34; return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_VARIANT, list) &gt;&gt;&gt; def ConvertArrays2Variant(inputdata, vartype=&#34;Variant&#34;): import pythoncom if vartype == &#34;ArrayofObjects&#34;: # 对象数组 outputdata = win32com." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcdabai.github.io/posts/fa792a4929e8f51f863156a617b42241/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2021-12-15T18:11:28+08:00" />
<meta property="article:modified_time" content="2021-12-15T18:11:28+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程大白的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程大白的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">图纸空间的打印测试</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p>研究测试了一天，搞定了。深入认真研究清楚一个问题，功力一下子就升了一级。</p> 
<pre><code>
&gt;&gt;&gt; # -*- coding: utf-8 -*-

&gt;&gt;&gt; from  pyautocad  import Autocad,APoint
&gt;&gt;&gt; import pyautocad.types
&gt;&gt;&gt; import math
&gt;&gt;&gt; import os
&gt;&gt;&gt; import time
&gt;&gt;&gt; import win32com.client
&gt;&gt;&gt; import pythoncom

&gt;&gt;&gt; def vtFloat(list):
    """列表转化为浮点数"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, list)

&gt;&gt;&gt; def vtInt(list):
    """列表转化为整数"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_I2, list)

&gt;&gt;&gt; def vtVariant(list):
    """列表转化为变体"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_VARIANT, list)

&gt;&gt;&gt; def ConvertArrays2Variant(inputdata, vartype="Variant"):
    import pythoncom
    if vartype == "ArrayofObjects":  # 对象数组
        outputdata = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, inputdata)
    if vartype == "Double":  # 双精度
        outputdata = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, inputdata)
    if vartype == "ShortInteger":  # 短整型
        outputdata = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_I2, inputdata)
    if vartype == "LongInteger":  # 长整型
        outputdata = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_I4, inputdata)
    if vartype == "Variant":  # 变体
        outputdata = win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_VARIANT, inputdata)
    return outputdata

&gt;&gt;&gt; acad = win32com.client.Dispatch("AutoCAD.Application")
&gt;&gt;&gt; acad.ActiveDocument.Utility.Prompt("Hello AutoCAD\n")
&gt;&gt;&gt; mp = acad.ActiveDocument.ModelSpace
&gt;&gt;&gt; print(acad.ActiveDocument.Name)
道路.dwg

&gt;&gt;&gt; def vtpnt(x, y, z=0):
    """坐标点转化为浮点数"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, (x, y, z))

					    
&gt;&gt;&gt; [pnt1, pnt2, pnt3, pnt4, pnt5, pnt6] = [vtpnt(-40, -40), vtpnt(500, 500), vtpnt(300, 200),
                                        vtpnt(600, 200), vtpnt(700, 200), vtpnt(100, 0)]
					    
&gt;&gt;&gt; def vtobj(obj):
    """转化为对象数组"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_DISPATCH, obj)

					    
&gt;&gt;&gt; def vtFloat(list):
    """列表转化为浮点数"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_R8, list)

					    
&gt;&gt;&gt; def vtInt(list):
    """列表转化为整数"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_I2, list)

					    
&gt;&gt;&gt; def vtVariant(list):
    """列表转化为变体"""
    return win32com.client.VARIANT(pythoncom.VT_ARRAY | pythoncom.VT_VARIANT, list)

					    
&gt;&gt;&gt; Padk = acad.ActiveDocument.PaperSpace
					    
&gt;&gt;&gt; CircleObj = Padk.AddCircle(pnt3, 1000)
					    
&gt;&gt;&gt; acad.ActiveDocument.SendCommand("_TILEMODE" + chr(13) + "0" + chr(13))
					    
&gt;&gt;&gt; ACADPref = acad.ActiveDocument.Application.preferences.Files
					    
&gt;&gt;&gt; originalValue = ACADPref.PrinterConfigPath \
    = r"C:\Users\Administrator\AppData\Roaming\Autodesk\AutoCAD 2011\R18.1\chs\Plotters"

&gt;&gt;&gt; currentPlot = acad.ActiveDocument.Plot
					    
&gt;&gt;&gt; currentLayout = acad.ActiveDocument.ActiveLayout
					    
&gt;&gt;&gt; currentLayout.ConfigName = "DWG To PDF.pc3"
					    
&gt;&gt;&gt; p1 = vtpnt(19357.8591776, 7161.9227564, z=0)
					    
&gt;&gt;&gt; p2 = vtpnt(20198.8591776, 6567.9227564, z=0)
					    
&gt;&gt;&gt; currentLayout.CanonicalMediaName = 'ISO_full_bleed_A1_(594.00_x_841.00_MM)'  # A*图纸
					    
&gt;&gt;&gt; currentLayout.PlotRotation = 0
					    
&gt;&gt;&gt; currentLayout.PlotRotation = 1

&gt;&gt;&gt; acad.ActiveDocument.Plot.DisplayPlotPreview
					    
&lt;bound method DisplayPlotPreview of &lt;COMObject &lt;unknown&gt;&gt;&gt;
&gt;&gt;&gt; acad.ActiveDocument.Plot.SetLayoutsToPlot
					    
&lt;bound method SetLayoutsToPlot of &lt;COMObject &lt;unknown&gt;&gt;&gt;

&gt;&gt;&gt; xs = 19357.8591776
					    
&gt;&gt;&gt; ys = 7161.9227564
					    
&gt;&gt;&gt; xe = 20198.8591776
					    
&gt;&gt;&gt; ye = 6567.9227564
					    
&gt;&gt;&gt; LowerLeft = [xs,ys]
					    
&gt;&gt;&gt; UpperRight = [xe,ye]
					    
&gt;&gt;&gt; LowerLeft = ConvertArrays2Variant(LowerLeft, "Double")
					    
&gt;&gt;&gt; UpperRight = ConvertArrays2Variant(UpperRight, "Double")

&gt;&gt;&gt; acad = win32com.client.Dispatch("AutoCAD.Application")
					    
&gt;&gt;&gt; acad.ActiveDocument.Utility.Prompt("Hello AutoCAD\n")
					    
&gt;&gt;&gt; print(acad.ActiveDocument.Name)
					    

&gt;&gt;&gt; currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.DisplayPlotPreview
					    
&lt;bound method DisplayPlotPreview of &lt;COMObject &lt;unknown&gt;&gt;&gt;

&gt;&gt;&gt; 

&gt;&gt;&gt; xs = 19357.8591776
					    
&gt;&gt;&gt; ys = 7161.9227564
					    
&gt;&gt;&gt; xe = 20198.8591776
					    
&gt;&gt;&gt; ye = 6567.9227564
					    
&gt;&gt;&gt; LowerLeft = [xs,ys]
					    
&gt;&gt;&gt; UpperRight = [xe,ye]
					    
&gt;&gt;&gt; LowerLeft = ConvertArrays2Variant(LowerLeft, "Double")
					    
&gt;&gt;&gt; UpperRight = ConvertArrays2Variant(UpperRight, "Double")
					    
&gt;&gt;&gt; currentPlot = acad.ActiveDocument.Plot
					    
&gt;&gt;&gt; currentLayout = acad.ActiveDocument.ActiveLayout
					    
&gt;&gt;&gt; currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
					    
&gt;&gt;&gt; acad.ActiveDocument.SendCommand("_TILEMODE" + chr(13) + "0" + chr(13))
					    
&gt;&gt;&gt; acad.ActiveDocument.SendCommand("_plot"+chr(13)+chr(13)+chr(13)+chr(13))
					    

&gt;&gt;&gt; currentLayout.PlotType = 4
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; print('重新测试，以上内容作废')
					    
重新测试，以上内容作废
&gt;&gt;&gt; #1首先连接控制cad
					    
&gt;&gt;&gt; acad = win32com.client.Dispatch("AutoCAD.Application")
					    
&gt;&gt;&gt; acad.ActiveDocument.Utility.Prompt("Hello AutoCAD\n")
					    
&gt;&gt;&gt; #如果一开始是布局空间，上面的连接命令就会出错
					    
&gt;&gt;&gt; Padk = acad.ActiveDocument.PaperSpace
					    
&gt;&gt;&gt; CircleObj = Padk.AddCircle(pnt3, 1800)
					    
&gt;&gt;&gt; acad.ActiveDocument.SendCommand("_TILEMODE" + chr(13) + "0" + chr(13))
					    
&gt;&gt;&gt; #进入图纸空间，看到刚才在图纸空间画的圆
					    
&gt;&gt;&gt; #将打印设置先不要设为窗口
					    
&gt;&gt;&gt; #现在来设定窗口
					    
&gt;&gt;&gt; xs = 19357.8591776
					    
&gt;&gt;&gt; ys = 7161.9227564
					    
&gt;&gt;&gt; xe = 20198.8591776
					    
&gt;&gt;&gt; ye = 6567.9227564
					    
&gt;&gt;&gt; LowerLeft = [xs,ys]
					    
&gt;&gt;&gt; UpperRight = [xe,ye]
					    
&gt;&gt;&gt; LowerLeft = ConvertArrays2Variant(LowerLeft, "Double")
					    
&gt;&gt;&gt; UpperRight = ConvertArrays2Variant(UpperRight, "Double")
					    
&gt;&gt;&gt; currentPlot = acad.ActiveDocument.Plot
					    
&gt;&gt;&gt; currentLayout = acad.ActiveDocument.ActiveLayout
					    
&gt;&gt;&gt; currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
					    
&gt;&gt;&gt; #看看上面的命令是不是改变了打印设置
					    
&gt;&gt;&gt; #还没有
					    
&gt;&gt;&gt; currentLayout.PlotType = 4
					    
Traceback (most recent call last):
  File "&lt;pyshell#120&gt;", line 1, in &lt;module&gt;
    currentLayout.PlotType = 4
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\client\dynamic.py", line 565, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
pywintypes.com_error: (-2147418111, '被呼叫方拒绝接收呼叫。', None, None)
&gt;&gt;&gt; #把查看打印设置的窗口关闭再来执行命令
					    
&gt;&gt;&gt; currentLayout.PlotType = 4
					    
&gt;&gt;&gt; #确实要关闭，再去查看
					    
&gt;&gt;&gt; #已经变成窗口
					    
&gt;&gt;&gt; #设置一下打印图纸的图号
					    
&gt;&gt;&gt; currentLayout.CanonicalMediaName = 'ISO_full_bleed_A1_(594.00_x_841.00_MM)'  # A*图纸
					    
Traceback (most recent call last):
  File "&lt;pyshell#126&gt;", line 1, in &lt;module&gt;
    currentLayout.CanonicalMediaName = 'ISO_full_bleed_A1_(594.00_x_841.00_MM)'  # A*图纸
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\client\dynamic.py", line 565, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
pywintypes.com_error: (-2147418111, '被呼叫方拒绝接收呼叫。', None, None)
&gt;&gt;&gt; #同样要关闭查看的打印窗口，再来
					    
&gt;&gt;&gt; currentLayout.CanonicalMediaName = 'ISO_full_bleed_A1_(594.00_x_841.00_MM)'  # A*图纸
					    
&gt;&gt;&gt; #非常OK
					    
&gt;&gt;&gt;  currentLayout.ConfigName = "DWG To PDF.pc3"
					    
SyntaxError: unexpected indent
&gt;&gt;&gt; currentLayout.ConfigName = "DWG To PDF.pc3"
					    
&gt;&gt;&gt; currentLayout.CenterPlot = True  # 居中打印
					    
&gt;&gt;&gt; #现在默认的是纵向，转过来
					    
&gt;&gt;&gt;  currentLayout.PlotRotation = 0
					    
SyntaxError: unexpected indent
&gt;&gt;&gt; currentLayout.PlotRotation = 1  # 横向打印0
					    
&gt;&gt;&gt; #在运行这个命令一次看是否又转回纵向
					    
&gt;&gt;&gt; currentLayout.PlotRotation = 1
					    
&gt;&gt;&gt; #还是横向
					    
&gt;&gt;&gt; currentLayout.PlotRotation = 1
					    
&gt;&gt;&gt; currentLayout.PlotRotation = 0
					    
&gt;&gt;&gt; currentLayout.PlotRotation = 0
					    
&gt;&gt;&gt; currentLayout.PlotRotation = 1
					    
&gt;&gt;&gt; #测试证明1是横向
					    
&gt;&gt;&gt; #根据模型空间的打印经验，最后一个plottofile应该可以了
					    
&gt;&gt;&gt; acad.ActiveDocument.SetVariable("BACKGROUNDPLOT", 0)
					    
&gt;&gt;&gt; #前台打印
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.QuietErrorMode = True
					    
&gt;&gt;&gt; #安静
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #是的打印了什么却没有
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #这次把打印线打出来了，这根线是画在图纸空间的
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #画了圆但只看到一点，比例的问题
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #现在我知道可能是比例的原因，实际上打印的区域在我们所选范围的很小的区域
					    
&gt;&gt;&gt; #至少我确认打印范围确实跑到图纸空间来了，只是没有显示视口中的模型对象
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #现在我知道文字都能打印，那就只剩一个问题，怎么让视口中的模型显现呢
					    
&gt;&gt;&gt; #在目前的状态下，让我们用人工来打印，结果和程序一样，这证明是设置的原因了
					    
&gt;&gt;&gt; #观察发现能打印的区域模型是空的，所以进入模型空间增加一些内容
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #通过将模型加密，显现了
					    
&gt;&gt;&gt; #那么现在证明就是比例没有认真搞而已
					    
&gt;&gt;&gt; #认真做一个测试样板模型，考虑以毫米为单位绘制一条4公里的道路
					    
&gt;&gt;&gt; #道路宽24米
					    
&gt;&gt;&gt; xs = 19357.8591776
					    
&gt;&gt;&gt; ys = 8114.0905217
					    
&gt;&gt;&gt; xe = 20412.3938689
					    
&gt;&gt;&gt; ye = 7805.1859568
					    
&gt;&gt;&gt; LowerLeft = [xs,ys]
					    
&gt;&gt;&gt; UpperRight = [xe,ye]
					    
&gt;&gt;&gt; LowerLeft = ConvertArrays2Variant(LowerLeft, "Double")
					    
&gt;&gt;&gt; UpperRight = ConvertArrays2Variant(UpperRight, "Double")
					    
&gt;&gt;&gt; currentPlot = acad.ActiveDocument.Plot
					    
&gt;&gt;&gt; currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #还有个鬼，就是没有设置布满图纸
					    
&gt;&gt;&gt; #查看layout在帮助文档的属性信息
					    
&gt;&gt;&gt; acad = win32com.client.Dispatch("AutoCAD.Application")
					    
&gt;&gt;&gt; acad.ActiveDocument.Utility.Prompt("Hello AutoCAD\n")
					    
&gt;&gt;&gt; print(acad.ActiveDocument.Name)
					    
道路.dwg
&gt;&gt;&gt; acad.ActiveDocument.SendCommand("_TILEMODE" + chr(13) + "0" + chr(13))
					    
&gt;&gt;&gt; #一时找不到布满图纸的选项，应该使用英文版的cad就能容易找到相应的词
					    
&gt;&gt;&gt; #采取默认法，将文件打印手工设置成布满图纸，打印一份，应用到布局。关闭，再打开文件
					    
&gt;&gt;&gt; #包括打印样式等都可以不控制，还有更强的适应性。重新打开，发现文件的布满图纸选项已经打钩
					    
&gt;&gt;&gt; #重新再控制进入图纸空间和窗口打印，其他不用重复输入，这就是shell终端的好处
					    
&gt;&gt;&gt; acad = win32com.client.Dispatch("AutoCAD.Application")
					    
&gt;&gt;&gt; acad.ActiveDocument.Utility.Prompt("Hello AutoCAD\n")
					    
&gt;&gt;&gt; print(acad.ActiveDocument.Name)
					    
道路.dwg
&gt;&gt;&gt; #注意图纸必须是模型空间状态，否则上述连接报错
					    
&gt;&gt;&gt; #进入图纸空间状态
					    
&gt;&gt;&gt; acad.ActiveDocument.SendCommand("_TILEMODE" + chr(13) + "0" + chr(13))
					    
&gt;&gt;&gt; xs = 19975.5145557
					    
&gt;&gt;&gt; ys = 8114.0905217
					    
&gt;&gt;&gt; xe = 20412.3938689
					    
&gt;&gt;&gt; ye = 7805.1859568
					    
&gt;&gt;&gt; LowerLeft = [xs,ys]
					    
&gt;&gt;&gt; UpperRight = [xe,ye]
					    
&gt;&gt;&gt; LowerLeft = ConvertArrays2Variant(LowerLeft, "Double")
					    
&gt;&gt;&gt; UpperRight = ConvertArrays2Variant(UpperRight, "Double")
					    
&gt;&gt;&gt; currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
					    
Traceback (most recent call last):
  File "&lt;pyshell#204&gt;", line 1, in &lt;module&gt;
    currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
  File "&lt;COMObject &lt;unknown&gt;&gt;", line 3, in SetWindowToPlot
pywintypes.com_error: (-2147023174, 'RPC 服务器不可用。', None, None)
&gt;&gt;&gt; currentPlot = acad.ActiveDocument.Plot
					    
&gt;&gt;&gt; currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
					    
Traceback (most recent call last):
  File "&lt;pyshell#206&gt;", line 1, in &lt;module&gt;
    currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
  File "&lt;COMObject &lt;unknown&gt;&gt;", line 3, in SetWindowToPlot
pywintypes.com_error: (-2147023174, 'RPC 服务器不可用。', None, None)
&gt;&gt;&gt; currentLayout = acad.ActiveDocument.ActiveLayout
					    
&gt;&gt;&gt; currentPlot = acad.ActiveDocument.Plot
					    
&gt;&gt;&gt; currentLayout.SetWindowToPlot(LowerLeft, UpperRight)
					    
&gt;&gt;&gt; #因为开关文件所以需要重新运行活动桌面的命令
					    
&gt;&gt;&gt; acad.ActiveDocument.Plot.PlotToFile(r"D:\pythonCAD\Shuchu" + '\ ' +'图纸空间1.pdf')
					    
True
&gt;&gt;&gt; #一击致命，成功了
					    
&gt;&gt;&gt; #分享给CSDN的网友吧，我从别人那里弄了很多东西学习，分享一些心得是应该的
					    
&gt;&gt;&gt; #惭愧，学了这么久python，今天才知道原来shell是这么用的，要晓得仅仅用F5在编辑器里跑进行复杂测试实在是太不方便了					    

</code></pre> 
<p style="text-align:center;"><img alt="" src="https://images2.imgbox.com/47/eb/YmpFQkp6_o.png"></p> 
<p></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/61dd8b79e4a8d83059dfce8f8de7f0ef/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">Linux部署Nacos启动报错：Could not find or load main class</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/23a63ef7441b250545e7c53fdea440c6/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">ERROR 1067 (42000): Invalid default value for ‘end_time‘ Mysql</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程大白的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>